name: reviewdog
on: [pull_request]
jobs:
    linter_name:
        name: runner / phpcs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oohnoitz/action-phpcs-wordpress@v1
              with:
                  github_token: ${{ secrets.GH_BOT_TOKEN }}
                  # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
                  reporter: github-pr-check
                  # Change reporter level if you need.
                  # GitHub Status Check won't become failure with warning.
                  level: error
                  phpcs_standard: './phpcs.xml'
